spring.application.name=appointment-service
server.port=8083

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.data.mongodb.uri=mongodb://localhost:27017/hospital_appointment_db

spring.thymeleaf.cache=false