spring.application.name=doctor-service
server.port=8082
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.data.mongodb.uri=mongodb://localhost:27017/hospital_doctor_db
spring.thymeleaf.cache=false